name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  snapcraft:
    runs-on: ubuntu-24.04
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Use Snapcraft
        run: |
          snapcraft
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          snapcraft upload --release=stable kubevpn_${RELEASE_VERSION}_amd64.snap
  snapcraft-arm:
    runs-on: ubuntu-24.04-arm
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Use Snapcraft
        run: |
          snapcraft
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          snapcraft upload --release=stable kubevpn_${RELEASE_VERSION}_arm64.snap